apiVersion: batch/v1
kind: Job
metadata:
  name: pre-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["echo","pre-sync"]
      restartPolicy: Never
  backoofLimit: 0